name: Wolf2789/spairs
description: Sorted items iterator for tables.
version: 0.1
author: 
  - email: wolf2789@gmail.com
    name: Dawid Bugajski
autoload:
  - type: global
    name: spairs
    path: spairs.lua